apiVersion: v1
kind: Secret
metadata:
  name: score-api-secrets
  namespace: tetris
type: Opaque
stringData:
  COSMOS_ENDPOINT: "https://<cosmos-account>.documents.azure.com:443/"
  COSMOS_KEY: "<cosmos-primary-key>"
