service:
  enabled: true
  type: LoadBalancer

ports:
  web:
    port: 8000
    expose:
      default: true
      port: 80
    protocol: TCP
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    port: 8443
    expose:
      default: true
      port: 443
    protocol: TCP

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.shubhrajitpallob.dev`)
    entryPoints:
      - web # Change to websecure later for security!
      - websecure
