name: Infrastructure CI & Security Scan

on:
    push:
        branches:
            - infra
        paths:
            - 'Terraform/**'
            - '.github/**'

permissions:
    id-token: write
    contents: read

jobs:
    code-security-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Set Up SAST for code scanning
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                scan-ref: './Terraform'
                format: 'sarif'
                output: 'terraform-trivy-results.sarif'
            
            - name: Upload Trivy SARIF Results
              uses: actions/upload-artifact@v3
              with:
                name: terraform-trivy-results
                path: terraform-trivy-results.sarif

            - name: Set Up Python for Checkov scan
              uses: actions/setup-python@v4
              with:
                python-version: '3.9'


            - name: Install Checkov
              run: pip install checkov

            - name: Run Checkov scan
              id: checkov-scan
              uses: bridgecrewio/checkov-action@master
              with:
                directory: './Terraform'
                framework: 'terraform'
                output_format: 'sarif'
                output_file_path: 'checkov-results.sarif'

            - name: Upload Checkov SARIF Results
              uses: actions/upload-artifact@v3
              with:
                name: checkov-results
                path: checkov-results.sarif
        
    validate-terraform-code:
        needs: code-security-scan
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.5.0

            - name: Initialize Terraform
              run: terraform -chdir=Terraform init

            - name: Validate Terraform
              run: terraform -chdir=Terraform validate

    infra-deploy:
        needs: validate-terraform-code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.5.0

            - name: Initialize Terraform
              run: terraform init
              working-directory: ./Terraform

            - name: Terraform Plan
              run: |-
                terraform plan \
                  -var="ssh_public_key=${{ secrets.AZURE_VM_KEY_PUB }}" \
                  -var="project_name=tetris" \
                  -var='aks_cluster_name=tetris-aks' \
                  -var='aks_dns_prefix=tetrisaks' \
                  -var='aks_node_count=3' \
                  -var='aks_node_vm_size=Standard_D4s_v5' \
                  -var='cosmos_account_name=tetriscosmosdbacct01' \
                  -var='cosmos_database_name=tetrisdb' \
                  -var='cosmos_container_name=scores' \
                  -out=tfplan
              working-directory: ./Terraform

            - name: Apply Terraform
              run: |
                terraform apply -auto-approve tfplan
              working-directory: ./Terraform

            - name: Terraform Output
              run: terraform output
              working-directory: ./Terraform
